### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by ozzy1873** [davejlin/flutter_ble_lib_ios_15#4]
From the name of the repository, it sounds like Android support is a secondary concern. Is that true?

I have been using the privatdoktor branch for a few months now with no issues, apart from lack of support for ios 15. I think that branch may have some improvements over the latest dotintent branch. You may want to do a compare to see what changed. I noticed that there is one Android compile warning when using your branch vs privatdoktor.

  flutter_ble_lib:
    git:
      url: git://github.com/privatdoktor/FlutterBleLib.git
      ref: privatdoktor

Thanks!

**Comment by davejlin** [comment]
Hi @ozzy1873 ...
I probably should have named this fork better lol.
At the time, `flutter_ble_lib` was broken for iOS 15, while fine for Android, hence the need for the fork for my project, hence the name.
Since then I've actually updated to support Android issues, such as #3 to support Android V2 embedding.
Were there other issues that need addressing?  Seems to work fine on Android for me.
Thanks for the reference to privatdoktor.
Dave

**Comment by ozzy1873** [comment]
Look like the compile warning is due to this line in FlutterBleLibPlugin.java:
import io.flutter.plugin.common.PluginRegistry.Registrar;

It appears you can just delete that line. I commented it out and my project still builds, but the warning is gone.

**Comment by davejlin** [comment]
@ozzy1873 thanks much ... I'll take a look

**Comment by ozzy1873** [comment]
No, thank **you**! 
You may want to do a compare between the privatdoktor project and your own to see if there are differences.

**Comment by davejlin** [comment]
@ozzy1873 Thanks, will do ...

I tried removing ```import io.flutter.plugin.common.PluginRegistry.Registrar;``` (in ```.../android/src/main/java/com/polidea/flutter_ble_lib/FlutterBleLibPlugin.java)```, but I get the below error as a result:

```
cannot find symbol
    public static void registerWith(Registrar registrar) {
                                    ^
  symbol:   class Registrar
  location: class FlutterBleLibPlugin
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_ble_lib_ios_15:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

Were you referring to a different file?

**Comment by ozzy1873** [comment]
Hmmm...I'm looking at C:\Users\john\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_ble_lib_ios_15-2.5.0\android\src\main\java\com\polidea\flutter_ble_lib\FlutterBleLibPlugin.java
I don't see the registerWIth method.

**Comment by davejlin** [comment]
@ozzy1873 

It's on line 97 in: https://github.com/davejlin/flutter_ble_lib_ios_15/blob/master/android/src/main/java/com/polidea/flutter_ble_lib/FlutterBleLibPlugin.java

It needs to be there, because I'm supporting both V1 and V2 now, per instructions here: https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

_Also, note that the plugin should still contain the static registerWith() method to remain compatible with apps that don’t use the v2 Android embedding. (See Upgrading pre 1.12 Android projects for details.) The easiest thing to do (if possible) is move the logic from registerWith() into a private method that both registerWith() and onAttachedToEngine() can call. Either registerWith() or onAttachedToEngine() will be called, not both._

**Comment by ozzy1873** [comment]
Odd, my file is different from what is in the repo and I am definitely pulling in 2.5.0. I'll remove the plugin and redownload.

**Comment by davejlin** [comment]
Hi @ozzy1873 ...
No worries at all - yeah that is weird!  Glad you could figured it out.
Btw, what is the exact warning you get?  I don't seem to get any warnings when I build, but maybe my warnings logging level is different from yours.

**Comment by ozzy1873** [comment]
Note: C:\Users\john\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_ble_lib_ios_15-2.5.0\android\src\main\java\com\polidea\flutter_ble_lib\FlutterBleLibPlugin.java uses or overr
ides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by davejlin** [comment]
Ah, ok, thanks ... yeah, makes sense.
